"""SFT v5: Fine-tune Gemma 3 270M IT on RAFT training data.

Base: TAPT ep1 (checkpoint-22, 46.2% citations — best from v3 sweep)
Data: 2142 samples (1729 oracle cited, 307 abstain, 106 memorize)
      Generated by Gemma 3 27B IT full precision via Gemini API
Loss: assistant-only (DataCollatorForCompletionOnlyLM)
      Fixes bug #3 from SFT v1-v3 (full-seq loss → echo behavior)

Standards:
- RAFT arXiv:2403.10131 (oracle + distractors + citations)
- DTA arXiv:2505.20871 (abstain for high-stakes)
- Google FFT: constant scheduler, dropout 0.0
- TRL DataCollatorForCompletionOnlyLM for assistant-only loss

Input:  pguillemin/pa-tapt-ep1-checkpoint (TAPT ep1 model)
        pguillemin/pa-sft-v5-data (sft_train_v5.jsonl)
Output: /kaggle/working/gemma-270m-sft-v5/
"""

from __future__ import annotations

import os

os.environ["CUDA_VISIBLE_DEVICES"] = "0"

import gc  # noqa: E402
import json  # noqa: E402
import logging  # noqa: E402
import math  # noqa: E402
import time  # noqa: E402

import torch  # noqa: E402

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)
t_start = time.time()

# -- PHASE 0: Environment --------------------------------------------------
logger.info("=== PHASE 0: Environment ===")
assert torch.cuda.is_available(), "FATAL: No GPU"
GPU_NAME = torch.cuda.get_device_name(0)
GPU_VRAM = torch.cuda.get_device_properties(0).total_memory / 1024**2
logger.info("GPU: %s (%.0f MB)", GPU_NAME, GPU_VRAM)

from transformers import AutoModelForCausalLM, AutoTokenizer  # noqa: E402
from trl import DataCollatorForCompletionOnlyLM, SFTConfig, SFTTrainer  # noqa: E402

# -- Config -----------------------------------------------------------------
SEED = 42
OUTPUT_DIR = "/kaggle/working" if os.path.isdir("/kaggle/working") else "."
MODEL_OUTPUT = os.path.join(OUTPUT_DIR, "gemma-270m-sft-v5")

# Hyperparameters — FRESH, not from v1-v4 (trained on regex garbage)
# Google FFT guide: constant scheduler, dropout 0.0
# LR 2e-5: TRL default for SFT, between TAPT 5e-6 and aggressive 5e-5
LR = 2e-5
EPOCHS = 3
BATCH_SIZE = 1
GRAD_ACCUM = 16  # effective batch = 16
MAX_SEQ_LENGTH = 1024  # P90 samples fit; max_seq_length=2048 → OOM on T4
WARMUP_RATIO = 0.1
SAVE_STEPS = 50  # ~8 checkpoints over 3 epochs (134 steps/epoch)

# Paths (dual Kaggle fallback)
_MODEL_PATHS = [
    "/kaggle/input/pa-tapt-ep1-checkpoint",
    "/kaggle/input/datasets/pguillemin/pa-tapt-ep1-checkpoint",
]
_DATA_PATHS = [
    "/kaggle/input/pa-sft-v5-data",
    "/kaggle/input/datasets/pguillemin/pa-sft-v5-data",
]

MODEL_PATH = next((p for p in _MODEL_PATHS if os.path.isdir(p)), None)
assert MODEL_PATH is not None, f"FATAL: Model not found: {_MODEL_PATHS}"

DATA_DIR = next((p for p in _DATA_PATHS if os.path.isdir(p)), None)
assert DATA_DIR is not None, f"FATAL: Data not found: {_DATA_PATHS}"
DATA_PATH = os.path.join(DATA_DIR, "sft_train_v5.jsonl")
assert os.path.exists(DATA_PATH), f"FATAL: {DATA_PATH} not found"

logger.info("Model: %s", MODEL_PATH)
logger.info("Data: %s", DATA_PATH)

# -- PHASE 1: Load model ---------------------------------------------------
logger.info("=== PHASE 1: Load model ===")

# fp32 model + AMP (fp16=True in trainer) — proven for Gemma 3 270M on T4
# DO NOT use torch.float16 — Gemma 3 fp16 = NaN (HF issue #36822)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_PATH,
    torch_dtype=torch.float32,
    device_map={"": 0},  # single GPU, NOT "auto"
    attn_implementation="eager",  # Gemma 3 safe
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

vram = torch.cuda.memory_allocated() / 1024**2
logger.info(
    "Model loaded: %.0f MB VRAM, %d params",
    vram,
    sum(p.numel() for p in model.parameters()),
)

# -- PHASE 2: Load data ----------------------------------------------------
logger.info("=== PHASE 2: Load data ===")

from datasets import Dataset  # noqa: E402

raw_data = []
with open(DATA_PATH, encoding="utf-8") as f:
    for line in f:
        raw_data.append(json.loads(line))
logger.info("Loaded %d training samples", len(raw_data))


# Format: apply chat template to get tokenizer-ready text
def format_chat(example: dict) -> dict:
    """Apply Gemma chat template to messages."""
    text = tokenizer.apply_chat_template(
        example["messages"], tokenize=False, add_generation_prompt=False
    )
    return {"text": text}


dataset = Dataset.from_list(raw_data)
dataset = dataset.map(format_chat, remove_columns=["messages"])
logger.info("Dataset formatted: %d samples", len(dataset))

# Inspect a sample
sample = dataset[0]["text"]
logger.info("Sample (first 300 chars): %s", sample[:300])

# -- PHASE 3: Train --------------------------------------------------------
logger.info("=== PHASE 3: Train ===")

# DataCollatorForCompletionOnlyLM: masks user tokens, loss only on assistant
# response_template = the token sequence that starts the model response
# For Gemma 3: "<start_of_turn>model\n"
response_template = "<start_of_turn>model\n"
collator = DataCollatorForCompletionOnlyLM(
    response_template=response_template,
    tokenizer=tokenizer,
)

steps_per_epoch = math.ceil(len(dataset) / (BATCH_SIZE * GRAD_ACCUM))
total_steps = steps_per_epoch * EPOCHS
logger.info(
    "Steps/epoch: %d, Total steps: %d, Save every: %d steps",
    steps_per_epoch,
    total_steps,
    SAVE_STEPS,
)

training_args = SFTConfig(
    output_dir=MODEL_OUTPUT,
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUM,
    learning_rate=LR,
    lr_scheduler_type="constant_with_warmup",  # Google FFT, not cosine
    warmup_ratio=WARMUP_RATIO,
    weight_decay=0.01,
    fp16=True,  # AMP handles fp16 cast (model stays fp32)
    bf16=False,
    gradient_checkpointing=True,
    max_seq_length=MAX_SEQ_LENGTH,
    logging_steps=10,
    save_steps=SAVE_STEPS,
    save_only_model=True,  # ~1.1 GB/checkpoint, not 3.1 GB
    save_total_limit=10,
    seed=SEED,
    report_to="none",
    dataset_text_field="text",
    eval_strategy="no",  # eval post-training to avoid OOM (vocab 262K)
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    data_collator=collator,
    processing_class=tokenizer,
)

logger.info("Starting training...")
train_result = trainer.train()
logger.info("Training complete: %s", train_result.metrics)

# Save final model
trainer.save_model(MODEL_OUTPUT)
tokenizer.save_pretrained(MODEL_OUTPUT)
logger.info("Model saved: %s", MODEL_OUTPUT)

# -- PHASE 4: Post-training eval -------------------------------------------
logger.info("=== PHASE 4: Quick eval ===")

# Free trainer memory for eval
del trainer
gc.collect()
torch.cuda.empty_cache()

model.eval()
vram = torch.cuda.memory_allocated() / 1024**2
logger.info("Post-training VRAM: %.0f MB", vram)

# Quick eval: generate 5 answers to verify format
eval_prompts = [
    "Tu es un assistant pour arbitres d'echecs.\nReponds UNIQUEMENT a partir du contexte ci-dessous.\n\nREGLES:\n1. Cite le document source et la page.\n2. Sois concis (3 phrases max).\n\nCONTEXTE:\nLA-octobre2025 (p.45):\nLe forfait d un joueur entraine la perte de la partie.\n\nQUESTION: Que se passe-t-il en cas de forfait ?",
    "Tu es un assistant pour arbitres d'echecs.\nReponds UNIQUEMENT a partir du contexte ci-dessous.\n\nREGLES:\n1. Cite le document source et la page.\n2. Si la reponse n'est pas dans le contexte, reponds 'Information non trouvee dans les extraits fournis.'\n\nCONTEXTE:\nR01_2025_26 (p.12):\nLes frais d inscription comprennent les droits d engagement.\n\nQUESTION: Quelle est la regle des 75 coups ?",
]

logger.info("=== EVAL SAMPLES ===")
for i, prompt in enumerate(eval_prompts):
    inputs = tokenizer(
        tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=False,
            add_generation_prompt=True,
        ),
        return_tensors="pt",
        truncation=True,
        max_length=MAX_SEQ_LENGTH,
    )
    inputs = {k: v.to(model.device) for k, v in inputs.items()}
    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=200,
            min_new_tokens=10,
            do_sample=True,
            temperature=0.2,
            top_k=64,
            top_p=0.95,
            repetition_penalty=1.2,
            no_repeat_ngram_size=4,
            pad_token_id=tokenizer.eos_token_id,
        )
    answer = tokenizer.decode(
        out[0][inputs["input_ids"].shape[1] :], skip_special_tokens=True
    )
    logger.info("--- Eval %d ---", i + 1)
    logger.info("  Q: %s", prompt.split("QUESTION: ")[-1][:80])
    logger.info("  A: %s", answer[:200])

# -- PHASE 5: Metrics ------------------------------------------------------
elapsed = (time.time() - t_start) / 60
metrics = {
    "model": "gemma-3-270m-it-tapt-ep1-sft-v5",
    "base": "TAPT ep1 (checkpoint-22, 46.2% citations)",
    "data": f"{len(raw_data)} samples (filtered from 2232, 90 invalid oracle removed)",
    "training_loss": train_result.metrics.get("train_loss", None),
    "training_runtime_s": train_result.metrics.get("train_runtime", None),
    "epochs": EPOCHS,
    "lr": LR,
    "scheduler": "constant_with_warmup",
    "effective_batch_size": BATCH_SIZE * GRAD_ACCUM,
    "max_seq_length": MAX_SEQ_LENGTH,
    "loss_type": "assistant_only (DataCollatorForCompletionOnlyLM)",
    "total_steps": total_steps,
    "save_steps": SAVE_STEPS,
    "elapsed_min": round(elapsed, 1),
    "gpu": GPU_NAME,
    "standards": [
        "RAFT arXiv:2403.10131",
        "DTA arXiv:2505.20871",
        "Google FFT: constant scheduler",
        "TRL DataCollatorForCompletionOnlyLM",
    ],
}
with open(os.path.join(MODEL_OUTPUT, "sft_v5_metrics.json"), "w") as f:
    json.dump(metrics, f, indent=2)

logger.info("=== DONE — %.1f min ===", elapsed)
logger.info("Metrics: %s", json.dumps(metrics, indent=2))
